<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>exercise_0_moveit2</name>
  <version>0.0.0</version>
  <description>Simple pick and place scenarios with industrial robots and gazebo. Aimed for beginners who want to learn basics of robotics with industrial robots.</description>
  <maintainer email="manuel.muth@rosiris.de">Manuel Muth</maintainer>
  <license>CC-BY-NC-SA-4.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rosiris_environment_description_common</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
